# Generated by Django 4.1.3 on 2022-11-26 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaDeportes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='update',
            new_name='updated',
        ),
    ]
