# Generated by Django 4.1.1 on 2022-11-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaDeportes', '0002_rename_update_producto_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Popular'), (3, 'Promo')], default=1),
        ),
    ]
